trigger: none # Manual trigger only

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AWSCLI@1
  displayName: "Test AWS Connection"
  inputs:
    awsCredentials: 'test' # Replace with your exact connection name
    regionName: 'us-east-2'                         # Replace with your target AWS region
    awsCommand: 'sts'
    awsSubCommand: 'get-caller-identity'
