trigger: none

stages:
# In Stage 1, run Terraform init and plan
- stage: plan
  displayName: 'Terraform Plan'
  jobs:
  - job: plan
    displayName: 'Terraform Init and Plan'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: TerraformInstaller@1
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      displayName: Run Terraform Init
      inputs:
        provider: 'aws'
        command: 'init'
        backendServiceAWS: 'Ado-aws-tfuser'
        backendAWSBucketName: 'kfabrik-645975910827-300526-bucket-hv4u8jx11xdjjm'
        backendAWSKey: 'development/terraform.tfstate'
    - task: TerraformTask@5
      name: terraformPlan
      displayName: Run Terraform Plan
      inputs:
        provider: 'aws'
        command: 'plan'
        commandOptions: '-out tfplan'
        environmentServiceNameAWS: 'Ado-aws-tfuser'
    # Only runs if the 'terraform plan' task has detected changes the in state.
    - task: TerraformTask@5
      displayName: Run Terraform Apply
      condition: and(succeeded(), eq(variables['terraformPlan.changesPresent'], 'true'))
      inputs:
        provider: 'aws'
        command: 'apply'
        commandOptions: 'tfplan'
        environmentServiceNameAWS: 'Ado-aws-tfuser'
